<!--
  RulesTab.vue
  ─────────────────────────────────────────────────────────────
  The Rulebook tab panel — shown when activeTab === 'rulebook'.
  Contains: story, how to play steps, rarity table, fairness info.
  This is the full inline tab version (not the modal overlay).
-->
<template>
  <div class="rules-wrap">

    <!-- Story card -->
    <div class="story-card">
      <h3>⚔ The Legend of VaultX</h3>
      <p>
        In the decentralised realm of Sui, ancient vaults hold mysterious
        artefacts of immense power. Long sealed by forgotten validators,
        these vaults are now accessible to any warrior brave enough to unlock them.
      </p>
      <p>
        No king, no admin, no single soul controls what lies within. The Sui
        Network's own randomness beacon — fed by dozens of independent validators —
        decides your fate. Not us. Not anyone. Pure on-chain chance.
      </p>
      <p>Your wallet is your identity. Your items are yours forever. Welcome to VaultX.</p>
    </div>

    <!-- How to play -->
    <div class="rule-block">
      <h4>How to Play</h4>
      <div class="rule-item"><div class="rule-num">1</div><span>Connect your Sui wallet — no signup required.</span></div>
      <div class="rule-item"><div class="rule-num">2</div><span>Buy a Loot Box for 0.1 SUI. You receive a sealed Box NFT in your wallet.</span></div>
      <div class="rule-item"><div class="rule-num">3</div><span>Open your box when ready. The Sui randomness beacon rolls 0–99 on-chain.</span></div>
      <div class="rule-item"><div class="rule-num">4</div><span>A GameItem NFT is minted to your wallet with a rarity tier and power level.</span></div>
      <div class="rule-item"><div class="rule-num">5</div><span>Transfer items to friends, or burn them. All actions are permanent on-chain.</span></div>
    </div>

    <!-- Rarity table -->
    <div class="rule-block">
      <h4>Rarity Tiers</h4>
      <table class="rarity-table">
        <thead>
          <tr>
            <th>Tier</th>
            <th>Roll Range</th>
            <th>Chance</th>
            <th>Power</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="r in rarities" :key="r.label">
            <td :style="{ color: r.color, fontWeight: 500 }">{{ r.label }}</td>
            <td class="dim">{{ r.rollRange }}</td>
            <td class="dim">{{ r.pct }}%</td>
            <td class="dim">{{ r.powerMin }} – {{ r.powerMax }}</td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Fairness -->
    <div class="rule-block">
      <h4>Fairness Guarantee</h4>
      <div class="rule-item">
        <div class="rule-num">✓</div>
        <span>Every roll is generated by Sui's randomness beacon at address
          <code>0x8</code> — verifiable by anyone.</span>
      </div>
      <div class="rule-item">
        <div class="rule-num">✓</div>
        <span>The raw roll (0–99) is published in the transaction event. You can verify your tier yourself.</span>
      </div>
      <div class="rule-item">
        <div class="rule-num">✓</div>
        <span>No admin, including the VaultX team, can predict or influence your outcome.</span>
      </div>
      <div class="rule-item" style="margin-bottom:0">
        <div class="rule-num">★</div>
        <span>Pity system: 30 consecutive non-Legendary opens guarantees Legendary on box 31.</span>
      </div>
    </div>

  </div>
</template>

<script>
import { RARITIES } from '../config/rarity.js'

export default {
  name: 'RulesTab',
  data() {
    return {
      // rollRange and pct are already fields on each RARITIES entry
      rarities: RARITIES,
    }
  },
}
</script>

<style scoped>
.rules-wrap { display: flex; flex-direction: column; gap: 1rem; }

/* Story card with green left border */
.story-card {
  background: #141422;
  border: 1px solid rgba(255,255,255,0.07);
  border-left: 3px solid #00ff88;
  border-radius: 6px;
  padding: 1.5rem;
}

.story-card h3 {
  font-family: 'Rajdhani', sans-serif;
  font-size: 1.05rem; font-weight: 600;
  letter-spacing: 0.05em;
  color: #00ff88;
  margin-bottom: 0.75rem;
}

.story-card p {
  color: #9090a8;
  font-size: 0.87rem;
  line-height: 1.7;
  margin-bottom: 0.6rem;
}
.story-card p:last-child { margin-bottom: 0; }

/* Rule blocks */
.rule-block {
  background: #141422;
  border: 1px solid rgba(255,255,255,0.07);
  border-radius: 6px;
  padding: 1.25rem 1.5rem;
}

.rule-block h4 {
  font-family: 'Rajdhani', sans-serif;
  font-size: 0.85rem; font-weight: 600;
  letter-spacing: 0.1em; text-transform: uppercase;
  color: #e8e8f0;
  margin-bottom: 1rem;
}

.rule-item {
  display: flex; align-items: flex-start; gap: 0.75rem;
  margin-bottom: 0.6rem;
  font-size: 0.85rem; color: #9090a8; line-height: 1.5;
}

.rule-num {
  width: 20px; height: 20px; flex-shrink: 0;
  background: rgba(0,255,136,0.08);
  border: 1px solid rgba(0,255,136,0.2);
  border-radius: 3px;
  display: flex; align-items: center; justify-content: center;
  font-size: 0.7rem; font-weight: 700; color: #00ff88;
  font-family: 'Rajdhani', sans-serif;
}

/* Rarity table */
.rarity-table {
  width: 100%; border-collapse: collapse; font-size: 0.82rem;
}

.rarity-table th {
  text-align: left; padding: 0.5rem 0.75rem;
  border-bottom: 1px solid rgba(255,255,255,0.07);
  color: #9090a8; font-size: 0.72rem;
  font-weight: 500; letter-spacing: 0.08em; text-transform: uppercase;
}

.rarity-table td { padding: 0.6rem 0.75rem; border-bottom: 1px solid rgba(255,255,255,0.03); }

.dim { color: #9090a8; }

code {
  font-family: monospace;
  color: #00ff88;
  font-size: 0.8rem;
}
</style>